### ISSUE TITLE
Role fails on "configure bridge interface for libvirt " on Ansible version 2.8

### ISSUE THREAD

**Issue by tosin2013** [flyemsafe/swygue.edge_host_setup#6]
The below task fails when using ansible 2.8. 

Workaround: downgrade to ansible 2.6 

TASK [swygue.edge_host_setup : configure bridge interface for libvirt] ****************************************************************************************
Friday 20 December 2019  15:16:38 -0500 (0:00:01.869)       0:00:34.560 ******* 
fatal: [localhost]: FAILED! => 
  reason: |-
    'with_libvirt_host_networks[1]s' is not a valid attribute for a Task
  
    The error appears to be in '/home/admin/qubinode-installer/playbooks/roles/swygue.edge_host_setup/tasks/bridge_interface.yml': line 6, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - fail: msg="Bailing out. this play requires libvirt_host_networks[1].bridge_device"
      ^ here
  
    This error can be suppressed as a warning using the "invalid_task_attribute_failed" configuration

**Comment by flyemsafe** [comment]
@tosin2013 Is this still an issue?
